version: '2.1'

services:

  web-service:
    container_name: web-service
    build: https://github.com/vbeausoleil/flask-microservices-client.git
    ports:
      - '3007:3000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      users-service:
        condition: service_started
    links:
      - users-service

  users-db:
    container_name: users-db
    build: https://github.com/vbeausoleil/flask-microservices-users.git#master:project/db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  users-service:
    container_name: users-service
    build: https://github.com/vbeausoleil/flask-microservices-users.git
    # command: gunicorn -b 0.0.0.0:5000 manage:app
    expose:
      - '5000'
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db
    
  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      users-service:
        condition: service_started
    links:
      - users-service